# Generated by Django 3.2.25 on 2024-06-10 05:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EmployeesNumber",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("to15", "до 15 человек"),
                            ("from15to50", "от 15 до 50 человек"),
                            ("from50to100", "от 50 до 100 человек"),
                            ("from100to500", "от 100 до 500 человек"),
                            ("from500", "более 500 человек"),
                            ("from1000", "более 1000 человек"),
                            ("from10000", "более 10000 человек"),
                        ],
                        help_text="Заполните количество сотрудников",
                        max_length=25,
                        unique=True,
                        verbose_name="количество сотрудников",
                    ),
                ),
            ],
            options={
                "verbose_name": "отрасль компании",
                "verbose_name_plural": "отрасли компании",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Link",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.URLField(
                        help_text="Укажите ссылку на ресурсы компании",
                        max_length=250,
                        verbose_name="ссылка на ресурсы компании",
                    ),
                ),
            ],
            options={
                "verbose_name": "ссылка на ресурсы компании",
                "verbose_name_plural": "ссылки на ресурсы компании",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("msk", "Москва"),
                            ("yerevan", "Ереван"),
                            ("spb", "Санкт-Петербург"),
                        ],
                        help_text="Заполните название города",
                        max_length=100,
                        unique=True,
                        verbose_name="название города",
                    ),
                ),
            ],
            options={
                "verbose_name": "Локация",
                "verbose_name_plural": "Локации",
            },
        ),
        migrations.CreateModel(
            name="Sector",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("agency", "Агентство"),
                            ("telecom", "Телекоммуникации"),
                            ("public_sector", "Госсектор"),
                            ("technologies", "Технологии"),
                            ("non-commercial", "Некоммерческие"),
                        ],
                        help_text="Заполните отрасль компании",
                        max_length=25,
                        unique=True,
                        verbose_name="отрасль компании",
                    ),
                ),
            ],
            options={
                "verbose_name": "отрасль компании",
                "verbose_name_plural": "отрасли компании",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        help_text="Введите название компании",
                        max_length=50,
                        null=True,
                        verbose_name="название компании",
                    ),
                ),
                (
                    "snippet",
                    models.TextField(
                        blank=True,
                        help_text="Заполните краткое описание компании",
                        max_length=250,
                        null=True,
                        verbose_name="краткое описание компании",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Заполните описание компании",
                        null=True,
                        verbose_name="описание компании",
                    ),
                ),
                (
                    "technologies",
                    models.TextField(
                        blank=True,
                        help_text="Заполните технологии компании",
                        null=True,
                        verbose_name="технологии компании",
                    ),
                ),
                (
                    "startup",
                    models.BooleanField(
                        default=False,
                        help_text="Заполните статус стартапа",
                        verbose_name="является ли компания стартапом",
                    ),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        help_text="Загрузите логотип компании",
                        null=True,
                        upload_to="companies/logo/",
                        verbose_name="логотип компании",
                    ),
                ),
                (
                    "profile_image",
                    models.ImageField(
                        blank=True,
                        help_text="Загрузите картинку профиля компании",
                        null=True,
                        upload_to="companies/profile_image/",
                        verbose_name="картинка профиля компании",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Дата формируется автоматически",
                        verbose_name="дата создания компании",
                    ),
                ),
                (
                    "employees_number",
                    models.ForeignKey(
                        blank=True,
                        help_text="Заполните количество сотрудников",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="companies",
                        to="companies.employeesnumber",
                        verbose_name="количество сотрудников",
                    ),
                ),
                (
                    "links",
                    models.ManyToManyField(
                        help_text="Укажите ссылки на ресурсы компании",
                        related_name="companies",
                        to="companies.Link",
                        verbose_name="ссылки на ресурсы компании",
                    ),
                ),
                (
                    "locations",
                    models.ManyToManyField(
                        help_text="Заполните локации компании",
                        related_name="companies",
                        to="companies.Location",
                        verbose_name="локации",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        help_text="Укажите владелеца компании",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="companies",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="владелец компании",
                    ),
                ),
                (
                    "sector",
                    models.ManyToManyField(
                        help_text="Выберите отрасли компании",
                        related_name="companies",
                        to="companies.Sector",
                        verbose_name="секторы",
                    ),
                ),
            ],
            options={
                "verbose_name": "компания",
                "verbose_name_plural": "компании",
                "ordering": ["-created_at"],
            },
        ),
    ]
