# Generated by Django 3.2.25 on 2024-06-10 18:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="employeesnumber",
            options={
                "ordering": ["name"],
                "verbose_name": "количество сотрудников компании",
                "verbose_name_plural": "количество сотрудников компании",
            },
        ),
        migrations.AlterField(
            model_name="company",
            name="links",
            field=models.ManyToManyField(
                blank=True,
                help_text="Укажите ссылки на ресурсы компании",
                related_name="companies",
                to="companies.Link",
                verbose_name="ссылки на ресурсы компании",
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="name",
            field=models.CharField(
                default=django.utils.timezone.now,
                help_text="Введите название компании",
                max_length=50,
                verbose_name="название компании",
            ),
            preserve_default=False,
        ),
    ]
