# Generated by Django 3.2.25 on 2024-06-10 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0003_alter_company_sector"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="name",
            field=models.CharField(
                help_text="Введите название компании",
                max_length=50,
                unique=True,
                verbose_name="название компании",
            ),
        ),
    ]
