# Generated by Django 3.2.25 on 2024-06-11 06:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0004_alter_company_name"),
        ("vacancies", "0002_alter_vacancy_employer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vacancy",
            name="employer",
            field=models.ForeignKey(
                help_text="Укажите работодателя",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="vacancies",
                to="companies.company",
                verbose_name="работодатель",
            ),
        ),
    ]
