# Generated by Django 3.2.25 on 2024-06-11 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vacancies", "0003_alter_vacancy_employer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vacancy",
            name="url",
            field=models.URLField(
                blank=True,
                help_text="Заполните урл вакансии",
                null=True,
                verbose_name="урл вакансии",
            ),
        ),
    ]
